version: "3.7"
services:
  # # nginx:
  # #   build: ./nginx
  # #   container_name: nginx
  # #   image: official_nginx
  # #   env_file: .env
  # #   ports:
  # #     - "${NGINX_PROXY}:${NGINX_PROXY}"
  # #     # - "443:443"

  #   depends_on:
  #     - server

  server:
    build: ./server
    image: server
    container_name: server
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3030:3030

    depends_on:
      - authdb
      - redis
    networks:
      - default

  authdb:
    build: ./mongodb
    container_name: authdb
    env_file: .env
    volumes:
      - ./postgres-data:/data/db
      - ./mongodb/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh
    ports:
      - 27018:27017
  redis:
    image: 'redis:alpine'
    container_name: redis
    env_file: .env
    ports:
        - 6379:6379
    sysctls:
        - net.core.somaxconn=1024
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/pi-coin
      POSTGRES_DB: pi-coin
      POSTGRES_HOST: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres-data: