version: "3.7"
services:
  server:
    build: ./server
    image: server
    container_name: server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3032:3032

    depends_on:
      - postgres
  
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      # POSTGRES_URL: postgres://admin:password@localhost:5432/pi-coin
      POSTGRES_DB: pi-coin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
